export { heroContent } from "./hero";
export { beforeAfterSectionContent } from "./before-after";
export { problemSectionContent } from "./problem";
export { solutionSectionContent } from "./solution";
export { levelSystemContent } from "./level-system";
export { benefitsSectionContent } from "./benefits";
export { trustSectionContent } from "./trust";
export { ctaSectionContent } from "./cta";
export { footerContent } from "./footer";
